#! /bin/sh

#START PROGRAMMES
pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
setxkbmap -layout ch -variant fr &
nitrogen --random --set-zoom-fill ~/.config/wallpaper/ &
sh -c `polybar example` & 
nm-applet &
xfce4-clipman &
picom --config $HOME/.config/bspwm/picom.conf &
dunst &
volumeicon &
thunar &
terminator & 
chromium &
rofi-change-theme &
~/.local/scripts/dorks.sh &

#MONITOR
bspc monitor -d I II III IV V VI VII VIII IX X

#DUAL MONITOR
#bspc monitor Virtual-0 -d 1 2 3 4 5
#bspc monitor Virutal-1 -d 6 7 8 9 10

#CONFIGURATION
bspc config border_width         	2
bspc config window_gap          	10
bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true bspc config ignore_ewmh_focus true

#BSPWM coloring
bspc config normal_border_color		"#7e7f80"
bspc config active_border_color		"#d15c02"
bspc config focused_border_color	"#d15c02"
bspc config presel_feedback_color	"#f55e27"
bspc config urgent_border_color 	"#dd2727"

#FULLSCREEN
bspc rule -a Mpv state=fullscreen

#FLOATING
bspc rule -a feh state=floating
bspc rule -a Galculator state=floating

#START DESKTOP
bspc rule -a code-oss desktop='^2' follow=off -o
bspc rule -a Chromium desktop='^1' follow=off -o
bspc rule -a Thunar desktop='^3' follow=off -o
bspc rule -a Terminator desktop='^4' follow=off -o
bspc rule -a Mpv desktop='^4' follow=on
